### ISSUE TITLE
add class name count on condition that have true or false result

### ISSUE THREAD

**Issue by omriLAnyvision** [JedWatson/classnames#186]
Suggestion
-----

Classnames should support add class by condition ( if true add this class else add this class )

For example
```javascript
classnames('some-class-name', { true: 'user-valid', false: 'user-invalid', condition: isTokenValid()  })
``` 

Please let me know if i should open a PR for this feature

**Comment by newyork-anthonyng** [comment]
I think you can do this already with:

```js
const condition = isTokenValid();
classnames("some-class-name", {
  "user-valid": condition,
  "user-invalid": condition
}); 
```

Also, adding the syntax you're suggesting introduces backward compatibility issues. See this CSS code snippet.

```css
.true {
  background-color: green;
}

.false {
  background-color: red;
}

.condition {
  background-color: blue;
}
```
The new syntax needs to detect if someone wants to use the `class by condition` suggested above, or simply have CSS classes named `true`, `false`, `condition`.
