### ISSUE TITLE
How to erase  or replace the properties of the conditional class from external component?

### ISSUE THREAD

**Issue by MenaiAla** [JedWatson/classnames#318]
Thank you @JedWatson for this project.

I faced this issue and I could not resolve it.

I have a component called `Flex`:

```tsx

import classNames from "classnames"
import { ForwardedRef, forwardRef } from "react"

import styles from "./Flex.module.css"
import { FlexProps } from "./Flex.type"

export const Flex = forwardRef((props: FlexProps, ref: ForwardedRef<HTMLDivElement>) => {
  const { children, direction, gap, style, className, ...restProps } = props

  return (
    <div
      ref={ref}
      className={classNames(
        styles.flex,
        {
          [styles.row]: direction === "row",
          [styles.column]: direction === "column",
        },
        className
      )}
      style={{ gap: gap || 0, ...style }}
      {...restProps}
      data-cy='core-flex'
    >
      {children}
    </div>
  )
})

Flex.displayName = "Flex"

```

This is its CSS:

```css

.flex {
  display: flex;
  gap: var(--space-1);
}

.row {
  flex-direction: row;
  align-items: center;
}

.column {
  flex-direction: column;
}

```

I used this Flex from other component:

```tsx

 <Flex direction='column' className={styles["description-container"]}>
            <Flex
              direction='column'
              style={{ marginTop: "var(--space-4)" }}
              className={classNames({
                [styles["attribute-content"]]: attribute.options.length > 0,
              })}
            >
              <Title size='sm' className={styles["attribute-name"]}>
                {attribute.name}
              </Title>
              <Title size='xs'>Beschreibung</Title>
              <Text className={styles["attribute-description"]}>{attribute.description}</Text>
            </Flex>
            <AttributeOptionsList options={attribute.options} />
          </Flex>
```

If you see the parent Flex which has a direction column ( Vertical display ) , however, I want to control this direction in both mobile and desktop screens without defining it directly in the Flex.

I used a class called `description-container`:

```css
@media screen and (min-width: 1440px) {
  .description-container {
    padding: var(--space-3) var(--space-8);
    flex-direction: row;
  }
}
```

As you see I expect the Flex should be a `row` bit it remains a `column`. I tried to use the same class name but it does not change.

How can I change the `flex-direction` externally of the Flex?
